In [4]:
import numpy as np

In [5]:
li = [1,2,3,4]
li2 = [[1,2,3],[4,5,6]]

In [6]:
np.array(li)

array([1, 2, 3, 4])

In [7]:
np.array(li2)

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#creating arrays with numpy methods
#with arange method

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [10]:
np.arange(1,1000,2)

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
       157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
       183, 185, 187, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207,
       209, 211, 213, 215, 217, 219, 221, 223, 225, 227, 229, 231, 233,
       235, 237, 239, 241, 243, 245, 247, 249, 251, 253, 255, 257, 259,
       261, 263, 265, 267, 269, 271, 273, 275, 277, 279, 281, 283, 285,
       287, 289, 291, 293, 295, 297, 299, 301, 303, 305, 307, 309, 311,
       313, 315, 317, 319, 321, 323, 325, 327, 329, 331, 333, 335, 337,
       339, 341, 343, 345, 347, 349, 351, 353, 355, 357, 359, 36

In [11]:
#with linspace which will generate 50 numbers
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [12]:
#with linspace which will generate 50 numbers
np.linspace(1,2,10) # 3rd argument is for the number of value

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [14]:
from numpy import random

In [15]:
np.random.rand() #this gets a float random number

0.7289730383247192

In [16]:
#to get a int random number
np.random.randint(1,99,50)

array([55, 33, 30, 34, 22, 67, 47, 19, 36, 46, 19, 85, 55,  5, 77, 45, 77,
       77, 87, 95, 68, 17, 61, 13, 95, 78, 52, 73, 32, 74,  6, 44, 62, 28,
       23, 74, 31,  5, 81,  3, 95, 82, 96, 91,  8, 37, 10, 78, 73, 25])

In [16]:
rate = np.random.randint(100,1000,15)

In [17]:
import statistics as st


In [18]:
st.mean(rate)

505

In [24]:
st.stdev(rate)

195.13328778042973

In [26]:
st.median(rate)

519

In [27]:
max(rate)

841

In [28]:
min(rate)

174

In [ ]:
st.