In [10]:
import numpy as np

In [11]:
np.linspace(1,8,20)

array([1.        , 1.36842105, 1.73684211, 2.10526316, 2.47368421,
       2.84210526, 3.21052632, 3.57894737, 3.94736842, 4.31578947,
       4.68421053, 5.05263158, 5.42105263, 5.78947368, 6.15789474,
       6.52631579, 6.89473684, 7.26315789, 7.63157895, 8.        ])

In [14]:
np.arange(1,67,2) #to auto generate odd numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65])

In [21]:
import random

random.randrange(300,999)

301

In [23]:
np.random.seed(14)
np.random.randint(300,999,15) #to randomly generate intergers automatically 

array([919, 644, 568, 706, 627, 658, 968, 950, 508, 873, 788, 966, 325,
       771, 791])

In [24]:
np.random.seed(14)
data = np.random.randint(300,999,15) #indexing specific item 

In [25]:
data

array([919, 644, 568, 706, 627, 658, 968, 950, 508, 873, 788, 966, 325,
       771, 791])

In [26]:
data[3]

706

In [27]:
data[0:3]

array([919, 644, 568])

In [28]:
data[3:8]

array([706, 627, 658, 968, 950])

In [29]:
#to reassign number 
data[2] = 444

In [30]:
data[2]

444

In [47]:
data [5] = np.random.randint(300,999)

In [48]:
data[5]

438

In [49]:
data

array([919, 644, 444, 706, 627, 438, 968, 950, 508, 873, 788, 966, 325,
       771, 791])

In [51]:
#to spread a certain number across
data[3:6] = 419

In [52]:
data

array([919, 644, 444, 419, 419, 419, 968, 950, 508, 873, 788, 966, 325,
       771, 791])

In [53]:
np.sum(data)

10204

In [54]:
sum(data)

10204

In [55]:
np.max(data)

968

In [56]:
max(data)

968