In [3]:
import numpy as np

In [4]:
np.linspace(1,8,20)

array([1.        , 1.36842105, 1.73684211, 2.10526316, 2.47368421,
       2.84210526, 3.21052632, 3.57894737, 3.94736842, 4.31578947,
       4.68421053, 5.05263158, 5.42105263, 5.78947368, 6.15789474,
       6.52631579, 6.89473684, 7.26315789, 7.63157895, 8.        ])

In [5]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [6]:
from numpy import random

In [7]:
np.random.rand()

0.5078900564593668

In [8]:
np.random.randint(1,99,50)

array([87, 18, 70, 29, 41, 37, 18, 32, 87, 53, 76, 52, 19, 32,  6, 23, 82,
       83, 55, 21, 38, 73, 88, 64, 37, 11, 91, 13, 39, 15, 69, 39,  6, 30,
       83, 21, 35,  2, 80, 67,  5, 44, 94, 43, 35, 25, 56, 59, 23, 33])